//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataSources
{
    using System;
    using System.Collections.Generic;
    /***
     * this class represent the entity update exist report
     ***/
    public partial class UpdatedReport
    {
        public string NewCoordinates { get; set; }
        public int ReportID { get; set; }
        public System.DateTime NewTime { get; set; }
        public int NumberOfHits { get; set; }
    
        public virtual Report Report { get; set; }
    }
}
